# Change these first
owner: Ariglad # Your GitHub username
repo: status_page # Your GitHub repository name

# Add your sites here
sites:
  - name: Ariglad app
    url: https://app.ariglad.com   
  - name: Ariglad website
    url: https://www.ariglad.com
  - name: TCP ping
    url: 1.1.1.1

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
#   cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /status_page
  logoUrl: https://app.ariglad.com/logo2.png
  name: Ariglad status page
  introTitle: "**Ariglad status page**"
  introMessage: Ariglad's status page - powered by Upptime on Github
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
